import { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    nav: {
      links: [
        { label: 'Services', href: 'services' },
        { label: 'Portfolio', href: 'portfolio' },
        { label: 'Why Us', href: 'why-us' },
        { label: 'Insights', href: 'blog' },
        { label: 'Pricing', href: 'pricing' },
        { label: 'Contact', href: 'contact' },
      ],
      cta: 'Get Started',
    },
    hero: {
      badge: 'Next Generation Web Agency',
      line1: 'We Build',
      line2: 'Digital Products',
      line3: 'That Scale',
      sub: 'NexWebi crafts modern websites, intelligent automation systems, and scalable SaaS platforms — engineered for performance, built for growth.',
      cta1: 'Start Your Project',
      cta2: 'View Our Work',
      trust: '5.0 rating · Trusted by 50+ businesses · USA & worldwide',
      stats: ['Projects Delivered', 'Client Satisfaction', 'Faster Delivery', 'Support'],
    },
    impactBar: {
      stats: [
        'Revenue generated for clients',
        'Projects shipped',
        'Countries served',
        'Average delivery time',
      ],
    },
    portfolio: {
      eyebrow: 'Our Work',
      title: 'Real Projects,',
      highlight: 'Real Results',
      sub: 'Every project we ship is production-ready, fully custom, and built to perform.',
      prompt: 'Want to see your project here?',
      cta: 'Start Your Project →',
    },
    process: {
      eyebrow: 'How We Work',
      title: 'Our Proven',
      highlight: 'Process',
      sub: 'Six clear steps from first conversation to long-term partnership — no surprises, no delays.',
      note: 'From discovery call to live product — typically',
      noteSpan: '2–6 weeks',
      noteEnd: 'depending on scope.',
      cta: 'Start the Process →',
    },
    services: {
      eyebrow: 'What We Build',
      title: 'Services That',
      highlight: 'Drive Results',
      sub: 'From idea to production — we deliver end-to-end digital solutions that combine cutting-edge technology with exceptional user experience.',
    },
    whyUs: {
      eyebrow: 'Why NexWebi',
      title: 'Built Different,',
      highlight: 'Built Better',
      sub: "We don't just build websites — we engineer digital experiences that perform, scale, and convert.",
      techLabel: 'Technologies We Master',
    },
    testimonials: {
      eyebrow: 'Client Stories',
      title: 'What Our',
      highlight: 'Clients Say',
      sub: 'Real feedback from businesses that trusted us to build their digital products.',
      featuredBadge: '✓ Launched 40% under budget',
    },
    pricing: {
      eyebrow: 'Transparent Pricing',
      title: 'Simple Plans,',
      highlight: 'Serious Results',
      sub: 'No hidden fees. No surprises. Every plan delivers real business value — not just a pretty website.',
      guarantees: ['🔒 Satisfaction Guaranteed', '📋 Source Code Ownership', '🤝 NDA Available', '📞 Free Discovery Call'],
      badge: '✓ All plans include source code ownership · NDA available · Dedicated project manager',
      customNote: 'Need something custom?',
      customLink: "Let's talk",
      customEnd: '— we build to any scope and budget.',
    },
    blog: {
      eyebrow: 'Insights & Expertise',
      title: 'We Know',
      highlight: 'What Works',
      sub: 'Practical knowledge from building real products — no fluff, no filler.',
      readArticle: 'Read Article',
    },
    faq: {
      eyebrow: 'FAQ',
      title: 'Common',
      highlight: 'Questions',
      sub: 'Everything you need to know before starting a project with us.',
      stillQ: 'Still have questions?',
      stillA: "Can't find what you're looking for? Send us a message and we'll get back to you within a few hours.",
      cta: 'Ask Us Directly',
      responseLabel: 'Average Response Time',
      responseValue: 'Under 2 hours',
    },
    cta: {
      badge: "Let's Build Together",
      h2a: 'Ready to Build Your',
      h2b: 'Next Digital Product?',
      sub: "Whether you have a fully scoped project or just a spark of an idea — we'll turn it into a product your users love.",
      urgency: '⚡ Currently accepting new projects — limited spots available',
      cta1: 'Start Your Project →',
      cta2: 'View Pricing',
      note: 'No commitment required · Free consultation · Response within 24h',
    },
    contact: {
      eyebrow: 'Get In Touch',
      title: 'Start Your',
      highlight: 'Project Today',
      sub: "Tell us about your project and we'll get back to you within 24 hours.",
      available: "We're Available Now",
      availableSub: 'Average response: under 2 hours',
      emailLabel: 'Email',
      hoursLabel: 'Hours',
      hoursValue: 'Mon–Fri · 9AM–6PM',
      hoursNote: 'GMT+1 · Emergency support 24/7',
      socialLabel: 'Follow Us',
      labels: { name: 'Full Name', email: 'Email', subject: 'Subject', message: 'Message' },
      placeholders: {
        name: 'Your full name',
        email: 'your@email.com',
        subject: "I'd like to build a SaaS platform...",
        message: 'Tell us about your project, goals, timeline...',
      },
      submit: 'Send Message',
      privacy: 'By submitting, you agree to our Privacy Policy. We never share your data.',
      successTitle: 'Message Sent!',
      successSub: "We'll get back to you within 24 hours.",
      sendAnother: 'Send Another',
      errors: {
        name: 'Name must be at least 2 characters',
        email: 'Please enter a valid email',
        message: 'Message must be at least 20 characters',
      },
    },
    footer: {
      desc: 'Building next-generation digital products — from modern websites to intelligent automation and scalable SaaS.',
      groups: {
        Services: [
          ['Web Development', 'services'],
          ['Automation', 'services'],
          ['SaaS Platforms', 'services'],
          ['E-commerce', 'services'],
          ['AI Integration', 'services'],
        ],
        Company: [
          ['Portfolio', 'portfolio'],
          ['Why NexWebi', 'why-us'],
          ['Insights', 'blog'],
          ['Pricing', 'pricing'],
        ],
        Legal: [
          ['Privacy Policy', 'privacy'],
          ['Terms of Service', 'terms'],
          ['Cookie Policy', 'cookie'],
        ],
      },
      copyright: 'All rights reserved.',
      builtBy: 'Built with',
      byNexWebi: 'by NexWebi',
      privacyPolicy: 'Privacy Policy',
      termsOfService: 'Terms of Service',
    },
  },

  fr: {
    nav: {
      links: [
        { label: 'Services', href: 'services' },
        { label: 'Portfolio', href: 'portfolio' },
        { label: 'Pourquoi Nous', href: 'why-us' },
        { label: 'Conseils', href: 'blog' },
        { label: 'Tarifs', href: 'pricing' },
        { label: 'Contact', href: 'contact' },
      ],
      cta: 'Commencer',
    },
    hero: {
      badge: 'Agence Web Nouvelle Génération',
      line1: 'Nous Créons',
      line2: 'Des Produits',
      line3: 'Qui Évoluent',
      sub: "NexWebi conçoit des sites web modernes, des systèmes d'automatisation intelligents et des plateformes SaaS évolutives — optimisées pour la performance, conçues pour la croissance.",
      cta1: 'Démarrer mon projet',
      cta2: 'Voir nos réalisations',
      trust: '5.0 de note · Approuvé par 50+ entreprises · USA & monde entier',
      stats: ['Projets livrés', 'Satisfaction client', 'Livraison plus rapide', 'Support'],
    },
    impactBar: {
      stats: [
        'Revenus générés pour nos clients',
        'Projets livrés',
        'Pays couverts',
        'Délai de livraison moyen',
      ],
    },
    portfolio: {
      eyebrow: 'Nos Réalisations',
      title: 'Vrais Projets,',
      highlight: 'Vrais Résultats',
      sub: 'Chaque projet que nous livrons est prêt pour la production, entièrement personnalisé et conçu pour performer.',
      prompt: 'Vous voulez voir votre projet ici ?',
      cta: 'Démarrer votre projet →',
    },
    process: {
      eyebrow: 'Comment Nous Travaillons',
      title: 'Notre',
      highlight: 'Processus',
      sub: 'Six étapes claires de la première conversation au partenariat long terme — sans surprises, sans retards.',
      note: "De l'appel découverte au produit en ligne — généralement",
      noteSpan: '2–6 semaines',
      noteEnd: 'selon la portée du projet.',
      cta: 'Démarrer le processus →',
    },
    services: {
      eyebrow: 'Ce Que Nous Créons',
      title: 'Services qui',
      highlight: 'Génèrent des Résultats',
      sub: "De l'idée à la production — nous livrons des solutions digitales complètes alliant technologies de pointe et expérience utilisateur exceptionnelle.",
    },
    whyUs: {
      eyebrow: 'Pourquoi NexWebi',
      title: 'Différemment construit,',
      highlight: 'Mieux construit',
      sub: "Nous ne faisons pas que créer des sites web — nous concevons des expériences digitales qui performent, évoluent et convertissent.",
      techLabel: 'Technologies que nous maîtrisons',
    },
    testimonials: {
      eyebrow: 'Témoignages Clients',
      title: 'Ce que disent nos',
      highlight: 'Clients',
      sub: "Retours réels d'entreprises qui nous ont fait confiance pour créer leurs produits digitaux.",
      featuredBadge: '✓ Livré 40% sous le budget',
    },
    pricing: {
      eyebrow: 'Tarification Transparente',
      title: 'Plans Simples,',
      highlight: 'Résultats Sérieux',
      sub: 'Aucun frais caché. Aucune surprise. Chaque plan délivre une vraie valeur métier — pas seulement un beau site.',
      guarantees: ['🔒 Satisfaction garantie', '📋 Propriété du code source', '🤝 NDA disponible', '📞 Appel découverte gratuit'],
      badge: '✓ Tous les plans incluent la propriété du code · NDA disponible · Chef de projet dédié',
      customNote: "Besoin d'une solution sur mesure ?",
      customLink: 'Parlons-en',
      customEnd: '— nous construisons selon votre scope et budget.',
    },
    blog: {
      eyebrow: 'Insights & Expertise',
      title: 'Nous Savons',
      highlight: 'Ce Qui Fonctionne',
      sub: 'Connaissances pratiques issues de la création de vrais produits — sans blabla, sans remplissage.',
      readArticle: "Lire l'article",
    },
    faq: {
      eyebrow: 'FAQ',
      title: 'Questions',
      highlight: 'Fréquentes',
      sub: 'Tout ce que vous devez savoir avant de démarrer un projet avec nous.',
      stillQ: 'Vous avez encore des questions ?',
      stillA: "Vous ne trouvez pas ce que vous cherchez ? Envoyez-nous un message et nous vous répondrons dans les heures qui suivent.",
      cta: 'Nous contacter directement',
      responseLabel: 'Temps de réponse moyen',
      responseValue: 'Moins de 2 heures',
    },
    cta: {
      badge: 'Construisons ensemble',
      h2a: 'Prêt à créer votre',
      h2b: 'Prochain produit digital ?',
      sub: "Que vous ayez un projet entièrement défini ou juste une idée — nous la transformerons en un produit que vos utilisateurs adoreront.",
      urgency: '⚡ Actuellement en acceptation de nouveaux projets — places limitées',
      cta1: 'Démarrer votre projet →',
      cta2: 'Voir les tarifs',
      note: 'Sans engagement · Consultation gratuite · Réponse sous 24h',
    },
    contact: {
      eyebrow: 'Contactez-nous',
      title: 'Démarrez votre',
      highlight: "Projet aujourd'hui",
      sub: 'Parlez-nous de votre projet et nous vous répondrons dans les 24 heures.',
      available: 'Nous sommes disponibles',
      availableSub: 'Réponse moyenne : moins de 2 heures',
      emailLabel: 'Email',
      hoursLabel: 'Horaires',
      hoursValue: 'Lun–Ven · 9h–18h',
      hoursNote: "GMT+1 · Support d'urgence 24/7",
      socialLabel: 'Suivez-nous',
      labels: { name: 'Nom complet', email: 'Email', subject: 'Sujet', message: 'Message' },
      placeholders: {
        name: 'Votre nom complet',
        email: 'votre@email.com',
        subject: 'Je voudrais créer une plateforme SaaS...',
        message: 'Parlez-nous de votre projet, vos objectifs, votre calendrier...',
      },
      submit: 'Envoyer le message',
      privacy: 'En soumettant, vous acceptez notre Politique de confidentialité. Nous ne partageons jamais vos données.',
      successTitle: 'Message envoyé !',
      successSub: 'Nous vous répondrons dans les 24 heures.',
      sendAnother: 'Envoyer un autre',
      errors: {
        name: 'Le nom doit contenir au moins 2 caractères',
        email: 'Veuillez saisir un email valide',
        message: 'Le message doit contenir au moins 20 caractères',
      },
    },
    footer: {
      desc: "Création de produits digitaux de nouvelle génération — des sites web modernes à l'automatisation intelligente et aux SaaS évolutifs.",
      groups: {
        Services: [
          ['Développement Web', 'services'],
          ['Automatisation', 'services'],
          ['Plateformes SaaS', 'services'],
          ['E-commerce', 'services'],
          ['Intégration IA', 'services'],
        ],
        Company: [
          ['Portfolio', 'portfolio'],
          ['Pourquoi NexWebi', 'why-us'],
          ['Conseils', 'blog'],
          ['Tarifs', 'pricing'],
        ],
        Legal: [
          ['Politique de confidentialité', 'privacy'],
          ["Conditions d'utilisation", 'terms'],
          ['Politique des cookies', 'cookie'],
        ],
      },
      copyright: 'Tous droits réservés.',
      builtBy: 'Créé avec',
      byNexWebi: 'par NexWebi',
      privacyPolicy: 'Politique de confidentialité',
      termsOfService: "Conditions d'utilisation",
    },
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');
  const t = translations[lang];
  const toggleLang = () => setLang(l => (l === 'en' ? 'fr' : 'en'));
  return (
    <LanguageContext.Provider value={{ lang, t, toggleLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
